### ISSUE TITLE
[Video Review] Let’s Build a Real Time Chat Application with Elixir and Phoenix

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/phoenix-chat-example#114]
The original comment from this is in the comment history -> check it there 👍

**Comment by nelsonic** [comment]
@LuchoTurtle excellent+detailed write-up! 😍 

***`this`*** repo is the OG **`Phoenix`** _long_ before there was **`LiveView`**. ⏳ 
We've kept it that way because _many_ **`Phoenix`** Apps still use this ("MVC+JS") approach. 🚀 
@SimonLab wrote this updated version **_with_ `LiveView`**: [dwyl/phoenix-**liveview**-chat-example](https://github.com/dwyl/phoenix-liveview-chat-example) 🎉 
But the OG is still so widely shared and has good SEO that it remains the most popular. ⭐ 

**`try`** searching for "phoenix chat tutorial" on Google Incognito: 
https://www.google.com/search?q=phoenix+chat+tutorial

![first-result-on-google](https://user-images.githubusercontent.com/194400/195603614-5852ba06-d37f-428f-b84a-57d449d4ad8a.png)

Yep, _our_ tutorial. that you kindly updated. 🙌  is el numero uno! 🥇 featured by Google Snippets. 🤖 
**`#SEOMasterPlan`** 😜 

I'm _very_ keen for us to record a high quality **`Video`** of **`this`** tutorial (and all our others!) for our **YT**. 📺 
Hence my obsession with recruiting you (given your mad vid production skillz!) 😉

**Comment by ndrean** [comment]
Version without Liveview, using channels

![image](https://user-images.githubusercontent.com/6793008/204125333-8da74abb-895e-4914-a71f-9ad4efb82386.png)

**Comment by ndrean** [comment]
![image](https://user-images.githubusercontent.com/6793008/204125672-59fb718d-bc97-4033-97ac-1fbcf064fb0f.png)

**Comment by nelsonic** [comment]
GOTO: #149
