### ISSUE TITLE
making AUTH_API_KEY available windows #261

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-chat-example#261]
The `source .env` command when adding the AUTH_API_KEY is not recognized in powershell / cmd, and I can't find an alternative. What is a work around?

**Comment by nelsonic** [comment]
Switch to `mac` / `Linux`? 🍏 🐧 😜 

But in all seriousness, thanks for opening this issue. 🫶 
Worth adding a generic "Windows" section to: https://github.com/dwyl/learn-environment-variables 🆕 
https://stackoverflow.com/questions/53961802/how-to-use-an-environment-variable-in-powershell-console
So that we can point to it in the future. 🙏

**Comment by MikeRund** [comment]
I found the correct commands for cmd! 
(https://adityawiguna.medium.com/use-env-on-phoenix-framework-0ea9d1b70546)

**Comment by MikeRund** [comment]
I'll add them to the file for any other future fools still on windows

**Comment by MikeRund** [comment]
Update, although all tests pass for auth the client still reports the error `ERROR: AUTH_API_KEY Environment Variable is not set`. Investigating

**Comment by nelsonic** [comment]
Ohhh ... interesting! Happy to take a look on your PC. 💭

**Comment by nelsonic** [comment]
Please write-up what we just figured out on your PC so future windows (sufferers) can skip the hurdle. 😉
